port: "8081"
url: "nats://127.0.0.1:4222"
cluster: "test-cluster"
client: "stan-sub"
subj: "test"
db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  password: "mysecretpassword"
  dbname: "postgres"
  sslmode: "disable"

